rules:
  comments:
    require-starting-space: false
    ignore-shebangs: true
    min-spaces-from-content: 1
  braces:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
    min-spaces-inside: 0
    max-spaces-inside: 1
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: true
  line-length: disable
  new-lines:
    type: unix
